# UAPI Header export list
# Top-level Makefile calls into asm-$(ARCH)
# List only non-arch directories below

header-y += linux/
header-y += sound/
ccflags-y += -Wno-error
ccflags-y += -Wno-error=misleading-indentation
ccflags-y += -Wno-error
ccflags-y += -Wno-error=misleading-indentation
