# Top-level Makefile calls into asm-$(ARCH)
# List only non-arch directories below
ccflags-y += -Wno-error
ccflags-y += -Wno-error=misleading-indentation
ccflags-y += -Wno-error
ccflags-y += -Wno-error=misleading-indentation
